# Generated by Django 5.1 on 2024-11-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('idcategoriaProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('ciCliente', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('idmesa', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('idConsumo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Abierto'), (2, 'Cerrado')], default=1)),
                ('total', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='restaurante_api.cliente')),
                ('idmesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='restaurante_api.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('idcategoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='restaurante_api.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('idConsumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='restaurante_api.consumo')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_consumo', to='restaurante_api.producto')),
            ],
        ),
    ]
