# Generated by Django 5.1 on 2024-12-02 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Mesero', 'Mesero'), ('Cajero', 'Cajero'), ('Administrador', 'Administrador')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Ocupada', 'Ocupada')], default='Libre', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesa',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='restaurante_api.area'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='restaurante_api.empleado'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idreserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('contacto', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='restaurante_api.cliente')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='restaurante_api.mesa')),
            ],
        ),
    ]
