# Generated by Django 5.1 on 2024-12-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_api', '0003_rol_alter_empleado_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de impuestos aplicables.', max_digits=5)),
                ('moneda', models.CharField(default='PYG', help_text="Código de la moneda utilizada, e.g., 'USD', 'EUR'.", max_length=3)),
                ('idioma', models.CharField(default='es', help_text="Código del idioma, e.g., 'es' para español.", max_length=10)),
                ('formato_impresion', models.CharField(default='PDF', help_text='Formato de impresión preferido.', max_length=100)),
            ],
        ),
    ]
