# Generated by Django 5.1 on 2024-12-03 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_api', '0004_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='restaurante_api.empleado'),
        ),
    ]
