# Generated by Django 5.1 on 2024-12-03 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_api', '0005_area_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='empleado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='restaurante_api.area'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Ocupada', 'Ocupada'), ('Reservada', 'Reservada')], default='Libre', max_length=10),
        ),
    ]
