# Generated by Django 5.1.3 on 2024-12-04 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_api', '0007_alter_consumo_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('idmediopago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstadoPedido',
            fields=[
                ('idtipoestado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='consumo',
            name='monto_propina',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumo',
            name='idmediopago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='restaurante_api.mediopago'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechapedido', models.DateTimeField(auto_now_add=True)),
                ('totalpedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_entrega', models.CharField(max_length=100)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurante_api.cliente')),
                ('idempleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurante_api.empleado')),
                ('idmediopago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurante_api.mediopago')),
                ('idestadopedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurante_api.tipoestadopedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='restaurante_api.producto')),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='restaurante_api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='restaurante_api.pedido')),
                ('idtipoestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='restaurante_api.tipoestadopedido')),
            ],
        ),
    ]
